PAYLOADS = [{'type': 'topic',
  'course_id': 27,
  'entity_id': 1283,
  'topic_type': 'EscolaLms\\TopicTypeGift\\Models\\GiftQuiz',
  'course_language': 'en',
  'callback_url': 'https://wplms.travely24.com/api/webhook/summary/topic',
  'data': {'title': 'Quiz',
           'description': None,
           'introduction': 'Ok12',
           'topicable_class': 'EscolaLms\\TopicTypeGift\\Models\\GiftQuiz',
           'gift': 'theProject',
           'topic_json': {'reasoningQuiz': True},
           'questions_count': 4,
           'questions': [{'question': 'What type of computer performs calculations using the principles of quantum '
                          'mechanics? {=Quantum computer=A quantum computer}',
                          'type': 'short_answers',
                          'max_score': 25},
                         {'question': 'What is the basic unit of information in a quantum computer, which can '
                          'represent more than just 0 or 1? {=Qubit=Qubits}',
                          'type': 'short_answers',
                          'max_score': 25},
                         {'question': 'In contrast to quantum computers, what is the basic unit of information in '
                          'classical computers? {=Bit=Bits}',
                          'type': 'short_answers',
                          'max_score': 25},
                         {'question': 'What field of physics provides the principles that quantum computers use for '
                          'calculations? {=Quantum mechanics=The principles of quantum mechanics}',
                          'type': 'short_answers',
                          'max_score': 25}],
           'lesson_other_topics': [{'title': 'A quantum computer',
                                    'topicable_type': 'EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText',
                                    'text': 'A quantum computer is ==a type of computer that uses the principles of '
                                    'quantum mechanics to perform calculations==. Unlike classical computers '
                                    'that use bits to represent either a 0 or a 1, quantum computers use '
                                    '[qubits](https://www.google.com/search?q=qubits&sca_esv=3a8be7ffcaaa7a05&sxsrf=AE3TifPg9H41_gF0zRBglQXy13LuXW9IIg%3A1762240031788&ei=H6YJadLvL-qK7NYPvvbRmQ0&ved=2ahUKEwjV08GK-NeQAxXoSfEDHT0hCUMQgK4QegQIARAC&uact=5&oq=what+is+a+quantum+computer&gs_lp=Egxnd3Mtd2l6LXNlcnAiGndoYXQgaXMgYSBxdWFudHVtIGNvbXB1dGVyMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLAUjJzwNQ2sMDWNrDA3ADeACQAQCYAWOgAb4BqgEBMrgBA8gBAPgBAvgBAZgCBKACc8ICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFmAMAiAYBkAYKkgcDMy4xoAf-DrIHAzAuMbgHZsIHBTAuMy4xyAcL&sclient=gws-wiz-serp&mstk=AUtExfBiLCsd-EwPmWeqdfDYf8UJBMhe4L2FaqLkW1pXm-8pQb4h1GnDVC0CBnzquNlngxBzRjQwXeV55Cc_-CoxdjsBT81gYdaD2jAUyyKqRnF31ONhxfGFFND36L1id6RjV4wxS9frSLUUbrv63UMLe9PeGXTJvyG9QKyuPEAyRdQZJZ-W7P7cDXz5ii-nA3FjK5zD_L9yAYpIZrw0qLWBnTFm5hMOOMoPdgK0VJSqGy5HOLSetJv9XV1JS94P_KhP7XmKgT8F0kaG0AK4jzfapknc&csui=3) '
                                    'which can represent 0, 1, or both simultaneously through a property '
                                    'called superposition. This allows quantum computers to solve certain '
                                    'complex problems exponentially faster than traditional computers.\xa0\r\n'
                                    '\r\n'
                                    'How it works\r\n'
                                    '\r\n'
                                    '* '
                                    '**[Superposition](https://www.google.com/search?q=Superposition&sca_esv=3a8be7ffcaaa7a05&sxsrf=AE3TifPg9H41_gF0zRBglQXy13LuXW9IIg%3A1762240031788&ei=H6YJadLvL-qK7NYPvvbRmQ0&ved=2ahUKEwjV08GK-NeQAxXoSfEDHT0hCUMQgK4QegQIAxAB&uact=5&oq=what+is+a+quantum+computer&gs_lp=Egxnd3Mtd2l6LXNlcnAiGndoYXQgaXMgYSBxdWFudHVtIGNvbXB1dGVyMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLAUjJzwNQ2sMDWNrDA3ADeACQAQCYAWOgAb4BqgEBMrgBA8gBAPgBAvgBAZgCBKACc8ICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFmAMAiAYBkAYKkgcDMy4xoAf-DrIHAzAuMbgHZsIHBTAuMy4xyAcL&sclient=gws-wiz-serp&mstk=AUtExfBiLCsd-EwPmWeqdfDYf8UJBMhe4L2FaqLkW1pXm-8pQb4h1GnDVC0CBnzquNlngxBzRjQwXeV55Cc_-CoxdjsBT81gYdaD2jAUyyKqRnF31ONhxfGFFND36L1id6RjV4wxS9frSLUUbrv63UMLe9PeGXTJvyG9QKyuPEAyRdQZJZ-W7P7cDXz5ii-nA3FjK5zD_L9yAYpIZrw0qLWBnTFm5hMOOMoPdgK0VJSqGy5HOLSetJv9XV1JS94P_KhP7XmKgT8F0kaG0AK4jzfapknc&csui=3)**: '
                                    'A qubit can be in a state of both 0 and 1 at the same time, allowing a '
                                    'quantum computer to explore many possibilities concurrently.\r\n'
                                    '* '
                                    '**[Entanglement](https://www.google.com/search?q=Entanglement&sca_esv=3a8be7ffcaaa7a05&sxsrf=AE3TifPg9H41_gF0zRBglQXy13LuXW9IIg%3A1762240031788&ei=H6YJadLvL-qK7NYPvvbRmQ0&ved=2ahUKEwjV08GK-NeQAxXoSfEDHT0hCUMQgK4QegQIAxAD&uact=5&oq=what+is+a+quantum+computer&gs_lp=Egxnd3Mtd2l6LXNlcnAiGndoYXQgaXMgYSBxdWFudHVtIGNvbXB1dGVyMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLAUjJzwNQ2sMDWNrDA3ADeACQAQCYAWOgAb4BqgEBMrgBA8gBAPgBAvgBAZgCBKACc8ICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFmAMAiAYBkAYKkgcDMy4xoAf-DrIHAzAuMbgHZsIHBTAuMy4xyAcL&sclient=gws-wiz-serp&mstk=AUtExfBiLCsd-EwPmWeqdfDYf8UJBMhe4L2FaqLkW1pXm-8pQb4h1GnDVC0CBnzquNlngxBzRjQwXeV55Cc_-CoxdjsBT81gYdaD2jAUyyKqRnF31ONhxfGFFND36L1id6RjV4wxS9frSLUUbrv63UMLe9PeGXTJvyG9QKyuPEAyRdQZJZ-W7P7cDXz5ii-nA3FjK5zD_L9yAYpIZrw0qLWBnTFm5hMOOMoPdgK0VJSqGy5HOLSetJv9XV1JS94P_KhP7XmKgT8F0kaG0AK4jzfapknc&csui=3)**: '
                                    'This is a quantum phenomenon where qubits become linked, and the state of '
                                    'one qubit instantly influences the state of the other, no matter the '
                                    'distance between them.\r\n'
                                    '* '
                                    '**[Interference](https://www.google.com/search?q=Interference&sca_esv=3a8be7ffcaaa7a05&sxsrf=AE3TifPg9H41_gF0zRBglQXy13LuXW9IIg%3A1762240031788&ei=H6YJadLvL-qK7NYPvvbRmQ0&ved=2ahUKEwjV08GK-NeQAxXoSfEDHT0hCUMQgK4QegQIAxAF&uact=5&oq=what+is+a+quantum+computer&gs_lp=Egxnd3Mtd2l6LXNlcnAiGndoYXQgaXMgYSBxdWFudHVtIGNvbXB1dGVyMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLAUjJzwNQ2sMDWNrDA3ADeACQAQCYAWOgAb4BqgEBMrgBA8gBAPgBAvgBAZgCBKACc8ICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFmAMAiAYBkAYKkgcDMy4xoAf-DrIHAzAuMbgHZsIHBTAuMy4xyAcL&sclient=gws-wiz-serp&mstk=AUtExfBiLCsd-EwPmWeqdfDYf8UJBMhe4L2FaqLkW1pXm-8pQb4h1GnDVC0CBnzquNlngxBzRjQwXeV55Cc_-CoxdjsBT81gYdaD2jAUyyKqRnF31ONhxfGFFND36L1id6RjV4wxS9frSLUUbrv63UMLe9PeGXTJvyG9QKyuPEAyRdQZJZ-W7P7cDXz5ii-nA3FjK5zD_L9yAYpIZrw0qLWBnTFm5hMOOMoPdgK0VJSqGy5HOLSetJv9XV1JS94P_KhP7XmKgT8F0kaG0AK4jzfapknc&csui=3)**: '
                                    'Quantum computers can use interference to amplify the probability of '
                                    'correct answers and cancel out incorrect ones, much like waves can add up '
                                    'or cancel each other out.\xa0\r\n'
                                    '\r\n'
                                    "What it's used for\r\n"
                                    '\r\n'
                                    '* **Simulating complex systems**: Quantum computers can model and '
                                    'simulate quantum systems, which is useful for fields like drug discovery '
                                    'and materials science.\r\n'
                                    '* **Optimization**: They are excellent at solving optimization problems, '
                                    'such as finding the most fuel-efficient flight paths for aircraft or '
                                    'optimizing supply chains.\r\n'
                                    '* **Machine learning**: Quantum computers can accelerate certain machine '
                                    'learning algorithms, leading to breakthroughs in artificial '
                                    'intelligence.\xa0\r\n'
                                    '\r\n'
                                    'Key differences from classical computers\r\n'
                                    '\r\n'
                                    '* **Data representation**: Classical computers use bits (0 or 1), while '
                                    'quantum computers use qubits (0, 1, or both).\r\n'
                                    '* **Error correction**: Quantum computers are highly sensitive to their '
                                    'environment, which can cause errors. A major area of research is '
                                    'developing more robust error correction methods to overcome this '
                                    'challenge.\r\n'
                                    '* **Complementary technology**: Quantum computers are not intended to '
                                    'replace classical computers but to work alongside them to solve problems '
                                    'that are currently impossible for even the most powerful '
                                    'supercomputers.\xa0\r\n'
                                    '\r\n'
                                    '\\'}],
           'previous_lesson_summaries': []}},
 {'type': 'lesson',
  'course_id': 27,
  'entity_id': 564,
  'topic_type': None,
  'course_language': 'en',
  'callback_url': 'https://wplms.travely24.com/api/webhook/summary/lesson',
  'data': {'topic_summaries': ['Overview:\n'
                               'A quantum computer is a device that uses quantum-mechanical phenomena to perform '
                               'calculations. By using qubits, which can exist in multiple states at once, they can '
                               'solve certain complex problems exponentially faster than classical computers, opening '
                               'new frontiers in science and technology.\n'
                               '\n'
                               'Learning Objectives:\n'
                               '- Define a qubit and differentiate it from a classical bit.\n'
                               '- Explain the principles of superposition and entanglement in the context of quantum '
                               'computation.\n'
                               '- Compare the fundamental capabilities of quantum and classical computers.\n'
                               '- Identify potential real-world applications for quantum computing.\n'
                               '\n'
                               'Competency Rubric:\n'
                               '- **Conceptual Clarity:** Criterion: Articulates core quantum concepts. Evidence: '
                               'Defines qubit, superposition, and entanglement; explains their roles. Mastery: '
                               '0-Incorrect; 3-Partially correct; 5-Accurate and contextualized.\n'
                               '- **Comparative Analysis:** Criterion: Differentiates quantum from classical '
                               'computing. Evidence: Contrasts information units (qubit vs. bit); identifies suitable '
                               'problem types. Mastery: 0-No distinction; 3-Basic differences; 5-Explains key '
                               'performance distinctions.\n'
                               '- **Application Awareness:** Criterion: Identifies potential applications. Evidence: '
                               'Lists relevant fields (e.g., cryptography, medicine); explains why quantum is '
                               'advantageous. Mastery: 0-No examples; 3-Lists fields; 5-Explains relevance.\n'
                               '\n'
                               'Common Misconceptions:\n'
                               '- Quantum computers are universally faster than classical computers for all tasks.\n'
                               '- A qubit is literally a 0 and a 1 at the same time, not a probabilistic state.\n'
                               '- Quantum computers will make classical computers obsolete.\n'
                               '\n'
                               'Sample Checks:\n'
                               '- Explain the difference between how a classical computer and a quantum computer store '
                               'a single unit of information.\n'
                               '- Describe one potential application of quantum computing and explain why it is a good '
                               'fit for this technology.\n'
                               '\n'
                               'Prerequisites:\n'
                               '- Basic understanding of classical computers and binary bits.\n'
                               '\n'
                               'Keywords:\n'
                               'qubit, superposition, entanglement, quantum computing, classical computer, algorithm, '
                               'computation, decoherence, quantum mechanics',
                               'Overview:\n'
                               'This quiz assesses foundational knowledge of quantum computing, focusing on its core '
                               'concepts and terminology. Learners will demonstrate their understanding of what '
                               'distinguishes quantum computers from classical ones, preparing them for more advanced '
                               'topics in this emerging field.\n'
                               '\n'
                               'Learning Objectives:\n'
                               '- Define a quantum computer and the scientific principles it leverages.\n'
                               '- Identify the basic unit of information in a quantum computer (qubit).\n'
                               '- Differentiate between a qubit and a classical bit.\n'
                               '\n'
                               'Competency Rubric:\n'
                               '- Criterion: Foundational Knowledge — Defines core concepts of quantum computing.\n'
                               '  - Evidence: Correctly identifies a quantum computer; names the underlying scientific '
                               'field (quantum mechanics).\n'
                               '  - Mastery: 0: Fails to define key terms; 3: Defines one concept correctly; 5: '
                               'Accurately defines quantum computers and their scientific basis.\n'
                               '- Criterion: Terminology — Uses correct terminology for units of information.\n'
                               '  - Evidence: Correctly identifies the qubit as the quantum unit; correctly identifies '
                               'the bit as the classical unit.\n'
                               '  - Mastery: 0: Identifies neither unit; 3: Identifies one unit correctly; 5: '
                               'Accurately identifies both units in their respective contexts.\n'
                               '- Criterion: Comparative Understanding — Differentiates between quantum and classical '
                               'computing concepts.\n'
                               '  - Evidence: Implicitly distinguishes between quantum and classical computers; '
                               'explicitly contrasts the qubit and bit.\n'
                               '  - Mastery: 0: Shows no understanding of the differences; 3: Vaguely distinguishes '
                               'between paradigms; 5: Clearly differentiates between quantum and classical units of '
                               'information.\n'
                               '\n'
                               'Common Misconceptions:\n'
                               '- Quantum computers are just much faster versions of classical computers.\n'
                               '- A qubit is simply a bit that can be a 0 and 1 at the same time, without '
                               'understanding its probabilistic nature.\n'
                               '- The underlying science is something other than quantum mechanics.\n'
                               '\n'
                               'Sample Checks:\n'
                               '- Prompt: Explain the fundamental difference between the basic information units used '
                               'in classical and quantum computing.\n'
                               "- Prompt: What scientific field's principles are leveraged by a quantum computer for "
                               'its operations?\n'
                               '\n'
                               'Prerequisites:\n'
                               '- Basic familiarity with the concept of a classical computer.\n'
                               '- Understanding of a "bit" as the basic unit of information in classical computing.\n'
                               '\n'
                               'Keywords:\n'
                               'quantum computing, quantum mechanics, qubit, bit, classical computing, computation, '
                               'physics, information unit']}},
 {'type': 'topic',
  'course_id': 27,
  'entity_id': 1369,
  'topic_type': 'EscolaLms\\TopicTypeGift\\Models\\GiftQuiz',
  'course_language': 'en',
  'callback_url': 'https://wplms.travely24.com/api/webhook/summary/topic',
  'data': {'title': 'Quiz',
           'description': None,
           'introduction': None,
           'topicable_class': 'EscolaLms\\TopicTypeGift\\Models\\GiftQuiz',
           'gift': 'theProject',
           'questions_count': 5,
           'questions': [{'question': 'What term describes the mathematical representation of a quantum system that '
                          'holds all possible information about it? {=Quantum state}',
                          'type': 'short_answers',
                          'max_score': 10},
                         {'question': 'What is the basic unit of quantum information, analogous to a bit in classical '
                          'computing? {=Qubit=Quantum bit}',
                          'type': 'short_answers',
                          'max_score': 10},
                         {'question': 'What quantum principle allows a qubit to be in a combination of both 0 and 1 '
                          'states at the same time? {=Superposition}',
                          'type': 'short_answers',
                          'max_score': 10},
                         {'question': 'What is the name for the quantum phenomenon where multiple qubits are linked '
                          'and their states are correlated, no matter how far apart they are? '
                          '{=Entanglement=Quantum entanglement}',
                          'type': 'short_answers',
                          'max_score': 10},
                         {'question': 'According to the lesson material, what is one mathematical object used to '
                          'represent a quantum state? {=State vector=Wavefunction}',
                          'type': 'short_answers',
                          'max_score': 10}],
           'lesson_other_topics': [{'title': 'A quantum state',
                                    'topicable_type': 'EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText',
                                    'text': 'A quantum state is ==a mathematical description of a quantum system, like '
                                    'a particle, that contains all possible information about it==. It is '
                                    'represented by a state vector or '
                                    '[wavefunction](https://www.google.com/search?q=wavefunction&sca_esv=3a8be7ffcaaa7a05&sxsrf=AE3TifMWqwPwq09Dge5LZkrfNImwEg0eTw%3A1762240135861&ei=h6YJafClNMOLxc8P0sOnuQs&oq=what+is+a+quantum+&gs_lp=Egxnd3Mtd2l6LXNlcnAiEndoYXQgaXMgYSBxdWFudHVtICoCCAIyChAjGIAEGCcYigUyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywEyCBAAGIAEGMsBMggQABiABBjLATIIEAAYgAQYywFIoWRQ6hVY6hVwAXgBkAEAmAF8oAF8qgEDMC4xuAEByAEA-AEBmAICoAKGAcICChAAGLADGNYEGEfCAg0QABiABBiwAxhDGIoFmAMAiAYBkAYKkgcDMS4xoAefB7IHAzAuMbgHgQHCBwMyLTLIBwY&sclient=gws-wiz-serp&mstk=AUtExfCCJKa35LBpd9HifHnRzDhA6Kn_oYZ21EC5jDus_GXjTuGDvu1dg5uViN90gVr-9c0lsT-0Qg1mDRVufY4jDLdQgXIhwkPuZNNMnjMwSBfg3esCVNkjZinf5KR0kwSPVCvmQIEn00Nm2W3RGQS3MpmreTCIT7chGib8_OaGNwPKqtQ&csui=3&ved=2ahUKEwjpquWn-9eQAxUfRPEDHZFKMXYQgK4QegQIAhAE) '
                                    "and determines the probabilities of the system's properties when "
                                    'measured. Quantum states change according to quantum rules and can '
                                    'exhibit behaviors like superposition, which is impossible for classical '
                                    'objects.\xa0\r\n'
                                    '\r\n'
                                    '* **Describes a quantum system:** A quantum state provides a complete '
                                    'picture of a quantum system (like an atom or subatomic particle) at a '
                                    'given moment.\r\n'
                                    '* **Mathematical representation:** It is a mathematical object, such as a '
                                    "state vector or a wavefunction, that embodies the system's properties.\r\n"
                                    '* **Includes all measurable properties:** A quantum state encapsulates '
                                    'all the properties that can be measured simultaneously, such as an '
                                    "electron's spin or a photon's polarization.\r\n"
                                    '* **Predicts measurement outcomes:** It allows for predictions about the '
                                    'probabilities of different measurement results for the system.\r\n'
                                    '* **Evolves by quantum rules:** The state of the system changes over time '
                                    'according to the laws of quantum mechanics, which are different from the '
                                    'rules of classical physics. For example, a quantum system can "jump" from '
                                    'one state to another instantaneously, unlike a classical object that must '
                                    'move through the space in between.\xa0\r\n'
                                    '\r\n'
                                    '\\'}],
           'previous_lesson_summaries': ['Overview:\n'
                                         'This lesson introduces quantum computing, which uses quantum-mechanical '
                                         'phenomena for calculations. Learners will explore the qubit, the fundamental '
                                         'unit of quantum information, and see how principles like superposition and '
                                         'entanglement enable quantum computers to solve certain complex problems '
                                         'exponentially faster than classical ones.\n'
                                         '\n'
                                         'Learning Objectives:\n'
                                         '- Define a qubit and differentiate it from a classical bit.\n'
                                         '- Explain the principles of superposition and entanglement in the context of '
                                         'quantum computation.\n'
                                         '- Compare the fundamental capabilities of quantum and classical computers.\n'
                                         '- Identify potential real-world applications for quantum computing and '
                                         'explain their relevance.\n'
                                         '\n'
                                         'Competency Rubric:\n'
                                         '- **Conceptual Clarity:** Criterion: Articulates core quantum concepts. '
                                         'Evidence: Defines qubit, superposition, and entanglement; explains their '
                                         'roles. Mastery: 0-Incorrect; 3-Partially correct; 5-Accurate and '
                                         'contextualized.\n'
                                         '- **Comparative Analysis:** Criterion: Differentiates quantum from classical '
                                         'computing. Evidence: Contrasts qubit vs. bit; identifies suitable problem '
                                         'types. Mastery: 0-No distinction; 3-Basic differences; 5-Explains key '
                                         'performance distinctions.\n'
                                         '- **Application Awareness:** Criterion: Identifies potential applications. '
                                         'Evidence: Lists relevant fields; explains the quantum advantage. Mastery: '
                                         '0-No examples; 3-Lists fields; 5-Explains relevance.\n'
                                         '\n'
                                         'Common Misconceptions:\n'
                                         '- Quantum computers are universally faster than classical computers for all '
                                         'tasks.\n'
                                         '- A qubit is literally a 0 and a 1 at the same time, not a probabilistic '
                                         'state.\n'
                                         '- Quantum computers will make classical computers obsolete.\n'
                                         '\n'
                                         'Key Takeaways:\n'
                                         '- Quantum computers use qubits, leveraging superposition and entanglement.\n'
                                         '- They excel at specific complex problems, not all computational tasks.\n'
                                         '- Quantum computing complements, rather than replaces, classical computing.\n'
                                         '- Key applications include drug discovery, materials science, and '
                                         'cryptography.']}},
 {'type': 'lesson',
  'course_id': 27,
  'entity_id': 570,
  'topic_type': None,
  'course_language': 'en',
  'callback_url': 'https://wplms.travely24.com/api/webhook/summary/lesson',
  'data': {'topic_summaries': ['Overview:\n'
                               "A quantum state is a system's complete mathematical description, containing all "
                               'possible information. This concept is foundational to quantum mechanics and its '
                               'applications in technology like quantum computing and medical imaging. Understanding '
                               'it is essential for describing how particles behave at the subatomic level.\n'
                               '\n'
                               'Learning Objectives:\n'
                               '- Define what a quantum state represents.\n'
                               '- Explain its mathematical representation (e.g., wavefunction).\n'
                               '- Describe how a state determines probabilities of measurement outcomes.\n'
                               '- Differentiate quantum evolution from classical behavior.\n'
                               '\n'
                               'Competency Rubric:\n'
                               '- Definition:\n'
                               '  - Criterion: Defines a quantum state.\n'
                               '  - Evidence: Identifies it as a complete mathematical description containing all '
                               'possible information.\n'
                               '  - Mastery: 0: Incorrect; 3: Vague; 5: Accurate and complete.\n'
                               '- Measurement Prediction:\n'
                               "  - Criterion: Explains the state's role in measurement.\n"
                               '  - Evidence: Links the state to probabilities of outcomes; avoids claiming definite '
                               'results pre-measurement.\n'
                               '  - Mastery: 0: Claims definite results; 3: Unclear on probability; 5: Explains '
                               'probabilistic link.\n'
                               '- Quantum Dynamics:\n'
                               '  - Criterion: Contrasts quantum and classical behavior.\n'
                               '  - Evidence: Differentiates quantum evolution from classical motion; mentions '
                               'superposition.\n'
                               '  - Mastery: 0: No differentiation; 3: States rules differ; 5: Contrasts with '
                               'examples.\n'
                               '\n'
                               'Common Misconceptions:\n'
                               '- A quantum state describes definite properties before measurement, not '
                               'probabilities.\n'
                               '- The wavefunction is a physical object rather than a mathematical abstraction.\n'
                               '- Quantum systems behave just like very small classical systems.\n'
                               '\n'
                               'Sample Checks:\n'
                               '- Contrast the "state" of a baseball in flight with the "quantum state" of an '
                               'electron.\n'
                               "- What information does a quantum state provide about a particle's spin before it is "
                               'measured?\n'
                               '\n'
                               'Prerequisites:\n'
                               '- Familiarity with classical physics concepts (e.g., position, momentum).\n'
                               '- Awareness of subatomic particles like electrons and photons.\n'
                               '\n'
                               'Keywords:\n'
                               'quantum state, wavefunction, state vector, superposition, quantum mechanics, '
                               'measurement, probability, quantum system',
                               'Overview:\n'
                               'This quiz assesses foundational knowledge of quantum computing principles. '
                               'Understanding these concepts is key to grasping how quantum computers can solve '
                               'complex problems intractable for classical machines, impacting fields from '
                               'cryptography to drug discovery.\n'
                               '\n'
                               'Learning Objectives:\n'
                               '- Define the quantum state and its mathematical representations.\n'
                               '- Identify the qubit as the basic unit of quantum information.\n'
                               '- Explain the principle of superposition and its effect on a qubit.\n'
                               '- Describe the phenomenon of quantum entanglement.\n'
                               '\n'
                               'Competency Rubric:\n'
                               '- **Conceptual Knowledge:**\n'
                               '  Criterion: Defines core quantum terminology.\n'
                               '  Evidence: Correctly identifies terms like qubit, superposition, and entanglement; '
                               'Associates quantum state with its representations.\n'
                               '  Mastery: 0-No correct definitions; 3-Partial definitions; 5-All definitions '
                               'correct.\n'
                               '- **Principle Application:**\n'
                               '  Criterion: Explains the function of key quantum principles.\n'
                               '  Evidence: Describes how superposition affects a qubit; Explains how entanglement '
                               'links multiple qubits.\n'
                               '  Mastery: 0-No explanations; 3-Partial explanation; 5-Clear explanations.\n'
                               '- **Distinguishing Concepts:**\n'
                               '  Criterion: Differentiates between classical and quantum ideas.\n'
                               '  Evidence: Contrasts a qubit with a classical bit; Recognizes entanglement as a '
                               'unique quantum correlation.\n'
                               '  Mastery: 0-Confuses concepts; 3-Partially differentiates; 5-Clearly differentiates.\n'
                               '\n'
                               'Common Misconceptions:\n'
                               '- Superposition is just an unknown state (0 or 1), not a true combination of both.\n'
                               '- Entanglement is the same as classical correlation or allows for faster-than-light '
                               'communication.\n'
                               '- A quantum state is a physical object rather than a mathematical description.\n'
                               '\n'
                               'Sample Checks:\n'
                               '- Explain how a qubit differs from a classical bit, referencing a specific quantum '
                               'principle.\n'
                               '- Describe the connection between two particles that are entangled.\n'
                               '- What is the purpose of a quantum state in describing a system?\n'
                               '\n'
                               'Prerequisites:\n'
                               "- Familiarity with the classical computing concept of a 'bit'.\n"
                               '- Exposure to introductory-level abstract scientific concepts.\n'
                               '\n'
                               'Keywords:\n'
                               'quantum computing, qubit, superposition, entanglement, quantum state, state vector, '
                               'wavefunction, quantum mechanics, quantum information']}},
 {'type': 'course',
  'course_id': 27,
  'entity_id': 27,
  'topic_type': None,
  'course_language': 'en',
  'callback_url': 'https://wplms.travely24.com/api/webhook/summary/course',
  'data': {'lesson_summaries': ['Overview:\n'
                                'This lesson introduces quantum computing, which uses quantum-mechanical phenomena for '
                                'calculations. Learners will explore the qubit, the fundamental unit of quantum '
                                'information, and see how principles like superposition and entanglement enable '
                                'quantum computers to solve certain complex problems exponentially faster than '
                                'classical ones.\n'
                                '\n'
                                'Learning Objectives:\n'
                                '- Define a qubit and differentiate it from a classical bit.\n'
                                '- Explain the principles of superposition and entanglement in the context of quantum '
                                'computation.\n'
                                '- Compare the fundamental capabilities of quantum and classical computers.\n'
                                '- Identify potential real-world applications for quantum computing and explain their '
                                'relevance.\n'
                                '\n'
                                'Competency Rubric:\n'
                                '- **Conceptual Clarity:** Criterion: Articulates core quantum concepts. Evidence: '
                                'Defines qubit, superposition, and entanglement; explains their roles. Mastery: '
                                '0-Incorrect; 3-Partially correct; 5-Accurate and contextualized.\n'
                                '- **Comparative Analysis:** Criterion: Differentiates quantum from classical '
                                'computing. Evidence: Contrasts qubit vs. bit; identifies suitable problem types. '
                                'Mastery: 0-No distinction; 3-Basic differences; 5-Explains key performance '
                                'distinctions.\n'
                                '- **Application Awareness:** Criterion: Identifies potential applications. Evidence: '
                                'Lists relevant fields; explains the quantum advantage. Mastery: 0-No examples; '
                                '3-Lists fields; 5-Explains relevance.\n'
                                '\n'
                                'Common Misconceptions:\n'
                                '- Quantum computers are universally faster than classical computers for all tasks.\n'
                                '- A qubit is literally a 0 and a 1 at the same time, not a probabilistic state.\n'
                                '- Quantum computers will make classical computers obsolete.\n'
                                '\n'
                                'Key Takeaways:\n'
                                '- Quantum computers use qubits, leveraging superposition and entanglement.\n'
                                '- They excel at specific complex problems, not all computational tasks.\n'
                                '- Quantum computing complements, rather than replaces, classical computing.\n'
                                '- Key applications include drug discovery, materials science, and cryptography.',
                                'Overview:\n'
                                'This lesson introduces the quantum state as the complete mathematical description of '
                                'a quantum system. Learners will explore how this foundational concept enables quantum '
                                'computing by examining the principles of superposition and entanglement. The focus is '
                                'on understanding how qubits, the basic units of quantum information, differ '
                                'fundamentally from classical bits.\n'
                                '\n'
                                'Learning Objectives:\n'
                                '- Define a quantum state and identify the qubit as the basic unit of quantum '
                                'information.\n'
                                '- Explain how a quantum state determines the probabilities of measurement outcomes.\n'
                                '- Describe the principles of superposition and entanglement and their effect on '
                                'qubits.\n'
                                '- Differentiate between quantum concepts (e.g., qubit) and their classical '
                                'counterparts (e.g., bit).\n'
                                '\n'
                                'Competency Rubric:\n'
                                '- **Conceptual Understanding**\n'
                                '  - Criterion: Defines core quantum terminology.\n'
                                '  - Evidence: Correctly defines quantum state, qubit, superposition, and '
                                'entanglement; Identifies the state as a mathematical description.\n'
                                '  - Mastery: 0: Incorrect definitions; 3: Partially defines key terms; 5: Accurately '
                                'and completely defines all terms.\n'
                                '- **Principle Application**\n'
                                '  - Criterion: Explains the function of key quantum principles.\n'
                                '  - Evidence: Links the quantum state to probabilistic measurement outcomes; '
                                'Describes how superposition affects a single qubit and how entanglement links '
                                'multiple qubits.\n'
                                '  - Mastery: 0: Incorrect explanations; 3: Vague on the role of probability or '
                                'entanglement; 5: Clearly explains the probabilistic nature of measurement and the '
                                'function of superposition and entanglement.\n'
                                '- **Classical vs. Quantum Differentiation**\n'
                                '  - Criterion: Contrasts quantum and classical concepts.\n'
                                '  - Evidence: Differentiates a qubit from a classical bit; Contrasts quantum '
                                'evolution (superposition) with deterministic classical motion.\n'
                                '  - Mastery: 0: Confuses quantum and classical ideas; 3: States that rules differ but '
                                'provides no detail; 5: Clearly contrasts concepts with specific examples.\n'
                                '\n'
                                'Common Misconceptions:\n'
                                '- A quantum state describes definite properties before measurement, not '
                                'probabilities.\n'
                                '- Superposition means a qubit is in an unknown classical state (0 or 1), rather than '
                                'a true combination of both.\n'
                                '- Entanglement is the same as classical correlation or allows for faster-than-light '
                                'communication.\n'
                                '\n'
                                'Key Takeaways:\n'
                                '- A quantum state is a complete mathematical description containing all possible '
                                'information about a system.\n'
                                '- Quantum mechanics is probabilistic; a state provides probabilities for measurement '
                                'outcomes, not definite values.\n'
                                '- Qubits use superposition to represent multiple states simultaneously, enabling '
                                'massive parallel computation.\n'
                                '- Entanglement creates a unique, non-classical correlation between qubits that is '
                                'essential for quantum algorithms.']}}]
